/**
 * WhatsApp Tool Definitions (Phase 6).
 *
 * These are the ToolDefinition objects that get registered in the toolkit.
 * Each definition describes the tool's schema, category, risk level, and
 * model-facing description. The actual handler implementations are in the
 * individual tool files (session-tools.ts, messaging-tools.ts, etc.).
 *
 * Per Ground Rule 7, none of these tools take a sessionId parameter —
 * they all act on "the" single linked WhatsApp number.
 */
import type { ToolDefinition } from '@agentx/shared';

const CAT = 'communication' as const;

export const WHATSAPP_TOOLS: ToolDefinition[] = [
  // ═══ Phase 6.1 — Session Tools ═══
  {
    id: 'whatsapp_link_session',
    name: 'Link WhatsApp Session',
    description: 'Start the WhatsApp linking flow (QR code or pairing code)',
    modelDescription: 'Start the WhatsApp session linking flow. Returns a QR code (scan with WhatsApp → Settings → Linked Devices → Link a Device) or instructs to use whatsapp_request_pairing_code. Use this when WhatsApp is not yet linked or has been disconnected.',
    category: CAT,
    riskLevel: 'medium',
    schema: { type: 'object', properties: {}, required: [] },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_get_session_status',
    name: 'WhatsApp Session Status',
    description: 'Get the current WhatsApp session status, QR code, and connection info',
    modelDescription: 'Check the WhatsApp session status (disconnected, qr_ready, ready, etc.). Returns the QR code data URL if available, phone number if linked, and any errors. Use this to check if WhatsApp is connected before sending messages.',
    category: CAT,
    riskLevel: 'low',
    schema: { type: 'object', properties: {}, required: [] },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_stop_session',
    name: 'Stop WhatsApp Session',
    description: 'Stop the active WhatsApp session (can be restarted later)',
    modelDescription: 'Stop the WhatsApp socket only. The QR link stays saved (like closing WhatsApp Web). whatsapp_link_session or an app restart reconnects without a new QR. Use whatsapp_unlink_session to remove the device.',
    category: CAT,
    riskLevel: 'medium',
    schema: { type: 'object', properties: {}, required: [] },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_unlink_session',
    name: 'Unlink WhatsApp Session',
    description: 'Permanently unlink WhatsApp and purge all stored credentials',
    modelDescription: 'Permanently unlink WhatsApp like logging out of WhatsApp Web: revoke the device on the phone and delete stored credentials. The owner must scan a new QR to link again. Do NOT use this for a temporary disconnect — stop keeps the link. Only unlink when they explicitly want the device removed.',
    category: CAT,
    riskLevel: 'high',
    schema: { type: 'object', properties: {}, required: [] },
    composable: false,
    source: 'builtin',
    isDestructive: true,
  },
  {
    id: 'whatsapp_request_pairing_code',
    name: 'Request WhatsApp Pairing Code',
    description: 'Get a phone-based pairing code as an alternative to QR scanning',
    modelDescription: 'Request a pairing code for linking WhatsApp without scanning a QR code. The user enters the code in WhatsApp → Settings → Linked Devices → Link a Device. Requires a phone number in international format (e.g. "15551234567"). The session must be in the linking flow (call whatsapp_link_session first).',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        phoneNumber: { type: 'string', description: 'Phone number in international format without + or spaces (e.g. "15551234567")' },
      },
      required: ['phoneNumber'],
    },
    composable: false,
    source: 'builtin',
  },

  // ═══ Phase 6.2 — Messaging Tools ═══
  {
    id: 'whatsapp_send_text',
    name: 'Send WhatsApp Text',
    description: 'Send a text message to a WhatsApp chat',
    modelDescription: 'Send a text message as the owner. chatId may be a saved name, first/last name, business name, nickname, phone, or JID (phone@c.us or group@g.us). The tool resolves names against the indexed address book — if several people match, it fails and you must ask the owner which one. Never invent a JID. When the recipient is not the owner, refer to the owner by the public identity in [USER] (pick one of the listed names at random, with prefix if set) — never by callsign.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'Contact name, business name, phone, or JID (e.g. "Mom", "Priya Pots", "15551234567", "15551234567@c.us")' },
        text: { type: 'string', description: 'Message text to send' },
        quotedMessageId: { type: 'string', description: 'Message ID to quote/reply to (optional)' },
        mentions: { type: 'array', items: { type: 'string' }, description: 'JIDs to mention (optional)' },
      },
      required: ['chatId', 'text'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_image',
    name: 'Send WhatsApp Image',
    description: 'Send an image file to a WhatsApp chat',
    modelDescription: 'Send an image (JPG, PNG, GIF, WebP) to a WhatsApp chat. filePath is resolved relative to the agent workspace. Optional caption is sent with the image.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        filePath: { type: 'string', description: 'Path to the image file' },
        caption: { type: 'string', description: 'Caption text (optional)' },
      },
      required: ['chatId', 'filePath'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_video',
    name: 'Send WhatsApp Video',
    description: 'Send a video file to a WhatsApp chat',
    modelDescription: 'Send a video (MP4, WebM, MOV) to a WhatsApp chat. filePath is resolved relative to the agent workspace. Optional caption is sent with the video.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        filePath: { type: 'string', description: 'Path to the video file' },
        caption: { type: 'string', description: 'Caption text (optional)' },
      },
      required: ['chatId', 'filePath'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_audio',
    name: 'Send WhatsApp Audio',
    description: 'Send an audio file or voice note to a WhatsApp chat',
    modelDescription: 'Send an audio file (MP3, OGG, M4A) to a WhatsApp chat. Set ptt=true to send as a voice note (push-to-talk) instead of a regular audio file.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        filePath: { type: 'string', description: 'Path to the audio file' },
        ptt: { type: 'boolean', description: 'Send as voice note (push-to-talk) instead of audio file (default: false)' },
      },
      required: ['chatId', 'filePath'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_document',
    name: 'Send WhatsApp Document',
    description: 'Send a document file to a WhatsApp chat',
    modelDescription: 'Send a document (PDF, DOCX, XLSX, TXT, etc.) to a WhatsApp chat. filePath is resolved relative to the agent workspace. Optional caption and fileName can be specified.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        filePath: { type: 'string', description: 'Path to the document file' },
        caption: { type: 'string', description: 'Caption text (optional)' },
        fileName: { type: 'string', description: 'Display name for the file (optional, defaults to basename)' },
      },
      required: ['chatId', 'filePath'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_location',
    name: 'Send WhatsApp Location',
    description: 'Send a location pin to a WhatsApp chat',
    modelDescription: 'Send a location pin with latitude/longitude to a WhatsApp chat. Optional name and address can be included.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        latitude: { type: 'number', description: 'Latitude coordinate' },
        longitude: { type: 'number', description: 'Longitude coordinate' },
        name: { type: 'string', description: 'Location name (optional)' },
        address: { type: 'string', description: 'Location address (optional)' },
      },
      required: ['chatId', 'latitude', 'longitude'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_contact',
    name: 'Send WhatsApp Contact',
    description: 'Send a contact card to a WhatsApp chat',
    modelDescription: 'Send a contact card (vCard) with display name, phone number, and optional organization to a WhatsApp chat.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        displayName: { type: 'string', description: 'Contact display name' },
        phone: { type: 'string', description: 'Contact phone number' },
        organization: { type: 'string', description: 'Organization name (optional)' },
      },
      required: ['chatId', 'displayName', 'phone'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_poll',
    name: 'Send WhatsApp Poll',
    description: 'Send a poll to a WhatsApp chat',
    modelDescription: 'Send a poll with a question and multiple choice options to a WhatsApp chat. selectableCount specifies how many options a voter can select (default: 1).',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        question: { type: 'string', description: 'Poll question' },
        options: { type: 'array', items: { type: 'string' }, description: 'Poll options (2-12 options)' },
        selectableCount: { type: 'number', description: 'Number of options a voter can select (default: 1)' },
      },
      required: ['chatId', 'question', 'options'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_send_sticker',
    name: 'Send WhatsApp Sticker',
    description: 'Send a sticker to a WhatsApp chat',
    modelDescription: 'Send a sticker (WebP image) to a WhatsApp chat.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        filePath: { type: 'string', description: 'Path to the sticker file (WebP)' },
      },
      required: ['chatId', 'filePath'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_reply',
    name: 'Reply to WhatsApp Message',
    description: 'Reply to a specific message in a WhatsApp chat',
    modelDescription: 'Send a text message that quotes/replies to a specific message in a WhatsApp chat. This creates a threaded reply visible in the chat.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        quotedMessageId: { type: 'string', description: 'ID of the message to reply to' },
        text: { type: 'string', description: 'Reply text' },
      },
      required: ['chatId', 'quotedMessageId', 'text'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_forward',
    name: 'Forward WhatsApp Message',
    description: 'Forward a message from one chat to another',
    modelDescription: 'Forward a specific message from one WhatsApp chat to another. Provide the source chat ID, message ID, and destination chat ID.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'Destination WhatsApp chat JID' },
        sourceChatId: { type: 'string', description: 'Source WhatsApp chat JID' },
        messageId: { type: 'string', description: 'ID of the message to forward' },
      },
      required: ['chatId', 'sourceChatId', 'messageId'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_react',
    name: 'React to WhatsApp Message',
    description: 'Add or remove an emoji reaction to a message',
    modelDescription: 'Add an emoji reaction to a specific WhatsApp message, or remove an existing reaction by setting emoji to null/empty.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        messageId: { type: 'string', description: 'ID of the message to react to' },
        emoji: { type: 'string', description: 'Emoji to react with (null or empty to remove reaction)' },
      },
      required: ['chatId', 'messageId'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_edit_message',
    name: 'Edit WhatsApp Message',
    description: 'Edit a previously sent message',
    modelDescription: 'Edit the text of a previously sent WhatsApp message. Only messages sent within the last ~15 minutes can be edited.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        messageId: { type: 'string', description: 'ID of the message to edit' },
        newText: { type: 'string', description: 'New message text' },
      },
      required: ['chatId', 'messageId', 'newText'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_delete_message',
    name: 'Delete WhatsApp Message',
    description: 'Delete a message (for me or for everyone)',
    modelDescription: 'Delete a WhatsApp message. Set forEveryone=true to delete for all participants (only works within ~1 hour of sending). Default is delete-for-me only.',
    category: CAT,
    riskLevel: 'high',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        messageId: { type: 'string', description: 'ID of the message to delete' },
        forEveryone: { type: 'boolean', description: 'Delete for everyone (true) or just for me (false, default)' },
      },
      required: ['chatId', 'messageId'],
    },
    composable: false,
    source: 'builtin',
    isDestructive: true,
  },
  {
    id: 'whatsapp_get_message_history',
    name: 'Get WhatsApp Message History',
    description: 'Fetch persisted WhatsApp message history',
    modelDescription: 'Fetch WhatsApp messages stored since the session connected (text, image, video, documents, owner and Agent-X sends). Pass chatId (name or JID) and/or query (search body / sender). Default limit 50.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID or contact name (optional if query is set)' },
        query: { type: 'string', description: 'Search text in message body or sender name' },
        limit: { type: 'number', description: 'Maximum number of messages to fetch (default: 50)' },
      },
      required: [],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_get_reactions',
    name: 'Get WhatsApp Reactions',
    description: 'Get reactions on a specific message',
    modelDescription: 'Fetch all reactions (emojis + who reacted) on a specific WhatsApp message. Requires messageReactionsQuery capability.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        messageId: { type: 'string', description: 'ID of the message to get reactions for' },
      },
      required: ['chatId', 'messageId'],
    },
    composable: true,
    source: 'builtin',
  },

  // ═══ Phase 6.3 — Bulk Send-Safety Tools ═══
  {
    id: 'whatsapp_send_bulk',
    name: 'Send WhatsApp Bulk Messages',
    description: 'Send multiple messages to a chat with rate limiting',
    modelDescription: 'Send multiple text messages to a single WhatsApp chat with built-in rate limiting (delayMs between sends, default 2000ms). Returns a batch ID for tracking. Messages are sent sequentially, not in parallel. Use whatsapp_get_batch_status to check progress and whatsapp_cancel_batch to stop.',
    category: CAT,
    riskLevel: 'high',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID to send all messages to' },
        messages: { type: 'array', items: { type: 'string' }, description: 'Array of message texts to send' },
        delayMs: { type: 'number', description: 'Delay between sends in milliseconds (default: 2000)' },
      },
      required: ['chatId', 'messages'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_get_batch_status',
    name: 'Get WhatsApp Batch Status',
    description: 'Check the status of a bulk send batch',
    modelDescription: 'Check the progress of a bulk send batch (sent, failed, pending counts). Use the batchId returned by whatsapp_send_bulk.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        batchId: { type: 'string', description: 'Batch ID from whatsapp_send_bulk' },
      },
      required: ['batchId'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_cancel_batch',
    name: 'Cancel WhatsApp Batch',
    description: 'Cancel an ongoing bulk send batch',
    modelDescription: 'Cancel an ongoing bulk send batch. Already-sent messages cannot be unsent. The batch will stop after the current message completes.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        batchId: { type: 'string', description: 'Batch ID to cancel' },
      },
      required: ['batchId'],
    },
    composable: false,
    source: 'builtin',
  },

  // ═══ Phase 6.4 — Contact Tools ═══
  {
    id: 'whatsapp_check_number',
    name: 'Check WhatsApp Number',
    description: 'Check if a phone number is registered on WhatsApp',
    modelDescription: 'Check if a phone number has a WhatsApp account. Returns whether the number exists and its WhatsApp JID if it does. Provide the phone number in international format without + or spaces.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        phoneNumber: { type: 'string', description: 'Phone number in international format (e.g. "15551234567")' },
      },
      required: ['phoneNumber'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_block_contact',
    name: 'Block WhatsApp Contact',
    description: 'Block a WhatsApp contact',
    modelDescription: 'Block a WhatsApp contact by JID. Blocked contacts cannot send messages or see your status.',
    category: CAT,
    riskLevel: 'high',
    schema: {
      type: 'object',
      properties: {
        jid: { type: 'string', description: 'WhatsApp JID to block (e.g. "15551234567@c.us")' },
      },
      required: ['jid'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_unblock_contact',
    name: 'Unblock WhatsApp Contact',
    description: 'Unblock a WhatsApp contact',
    modelDescription: 'Unblock a previously blocked WhatsApp contact by JID.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        jid: { type: 'string', description: 'WhatsApp JID to unblock' },
      },
      required: ['jid'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_list_contacts',
    name: 'List WhatsApp Contacts',
    description: 'List all WhatsApp contacts',
    modelDescription: 'Browse the indexed WhatsApp address book (saved name, first/last, business name, profile name, phone, JID). Prefer whatsapp_resolve_contact when the owner names one person. Use search to filter.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        search: { type: 'string', description: 'Optional search filter (case-insensitive, matches contact name, notify name, or phone number)' },
        limit: { type: 'number', description: 'Maximum number of contacts to return (default 50, max 200)' },
      },
      required: [],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_get_contact',
    name: 'Get WhatsApp Contact',
    description: 'Get details for a specific WhatsApp contact',
    modelDescription: 'Get one WhatsApp contact by name, business name, phone, or JID. If several people match, returns the candidates — ask the owner which one. Do not guess.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        jid: { type: 'string', description: 'WhatsApp JID (optional if query is set)' },
        query: { type: 'string', description: 'Name, business name, phone, or JID' },
      },
      required: [],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_resolve_contact',
    name: 'Resolve WhatsApp Contact',
    description: 'Resolve a person the owner named to their WhatsApp JID',
    modelDescription: 'Look up the owner\'s WhatsApp address book by first name, last name, full saved name, business name, profile name, nickname, phone, or JID. Returns exactly one JID, or a short list to disambiguate. Never guess. Call this before sending or creating a standing order when the owner says a name.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'What the owner called the person (e.g. "Mom", "Priya Pots", "Lincoln High", "15551234567")' },
      },
      required: ['query'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_remember_contact_alias',
    name: 'Remember WhatsApp Contact Nickname',
    description: 'Teach Agent-X a nickname for a WhatsApp contact',
    modelDescription: 'Save a nickname the owner uses (Mom, School, Boss) for a unique WhatsApp contact. After this, whatsapp_resolve_contact and send tools accept that nickname. If the name is ambiguous, resolve first and pass jid.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        alias: { type: 'string', description: 'Nickname to remember (e.g. "Mom")' },
        query: { type: 'string', description: 'Unique name of the contact to attach the nickname to' },
        jid: { type: 'string', description: 'WhatsApp JID if already resolved' },
      },
      required: ['alias'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_sync_contacts',
    name: 'Sync WhatsApp Contacts',
    description: 'Refresh the indexed WhatsApp address book from the linked session',
    modelDescription: 'Pull the latest WhatsApp contacts (saved names, business names, profile names, numbers) into the local directory. Use if a name is missing after a recent save on the phone.',
    category: CAT,
    riskLevel: 'low',
    schema: { type: 'object', properties: {}, required: [] },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_get_profile_picture',
    name: 'Get WhatsApp Profile Picture',
    description: 'Get the profile picture URL for a WhatsApp contact',
    modelDescription: 'Get the profile picture URL for a WhatsApp contact by JID. Returns null if the contact has hidden their picture or not set one.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        jid: { type: 'string', description: 'WhatsApp JID' },
      },
      required: ['jid'],
    },
    composable: true,
    source: 'builtin',
  },

  // ═══ Phase 6.5 — Group Tools ═══
  {
    id: 'whatsapp_create_group',
    name: 'Create WhatsApp Group',
    description: 'Create a new WhatsApp group',
    modelDescription: 'Create a new WhatsApp group with a subject and initial participants. Requires groupManagement capability.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        subject: { type: 'string', description: 'Group name/subject' },
        participants: { type: 'array', items: { type: 'string' }, description: 'Initial participant JIDs' },
      },
      required: ['subject', 'participants'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_get_group_info',
    name: 'Get WhatsApp Group Info',
    description: 'Get information about a WhatsApp group',
    modelDescription: 'Get group info (subject, description, participants, admin list) for a WhatsApp group. Requires groupManagement capability.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID (e.g. "120363xxx@g.us")' },
      },
      required: ['groupId'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_add_participants',
    name: 'Add WhatsApp Group Participants',
    description: 'Add participants to a WhatsApp group',
    modelDescription: 'Add one or more participants to a WhatsApp group. Requires groupManagement capability and admin privileges in the group.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID' },
        participants: { type: 'array', items: { type: 'string' }, description: 'JIDs to add' },
      },
      required: ['groupId', 'participants'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_remove_participants',
    name: 'Remove WhatsApp Group Participants',
    description: 'Remove participants from a WhatsApp group',
    modelDescription: 'Remove one or more participants from a WhatsApp group. Requires groupManagement capability and admin privileges.',
    category: CAT,
    riskLevel: 'high',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID' },
        participants: { type: 'array', items: { type: 'string' }, description: 'JIDs to remove' },
      },
      required: ['groupId', 'participants'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_promote_participant',
    name: 'Promote WhatsApp Group Participant',
    description: 'Promote a participant to admin in a WhatsApp group',
    modelDescription: 'Promote a group participant to admin role. Requires groupManagement capability and admin privileges.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID' },
        participant: { type: 'string', description: 'JID to promote' },
      },
      required: ['groupId', 'participant'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_demote_participant',
    name: 'Demote WhatsApp Group Participant',
    description: 'Demote an admin to regular participant in a WhatsApp group',
    modelDescription: 'Demote a group admin to regular participant. Requires groupManagement capability and admin privileges.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID' },
        participant: { type: 'string', description: 'JID to demote' },
      },
      required: ['groupId', 'participant'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_set_group_subject',
    name: 'Set WhatsApp Group Subject',
    description: 'Change the name/subject of a WhatsApp group',
    modelDescription: 'Change the subject (name) of a WhatsApp group. Requires groupManagement capability and admin privileges.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID' },
        subject: { type: 'string', description: 'New group subject/name' },
      },
      required: ['groupId', 'subject'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_set_group_description',
    name: 'Set WhatsApp Group Description',
    description: 'Change the description of a WhatsApp group',
    modelDescription: 'Change the description of a WhatsApp group. Requires groupManagement capability and admin privileges.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID' },
        description: { type: 'string', description: 'New group description' },
      },
      required: ['groupId', 'description'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_leave_group',
    name: 'Leave WhatsApp Group',
    description: 'Leave a WhatsApp group',
    modelDescription: 'Leave a WhatsApp group. Requires groupManagement capability.',
    category: CAT,
    riskLevel: 'high',
    schema: {
      type: 'object',
      properties: {
        groupId: { type: 'string', description: 'WhatsApp group JID to leave' },
      },
      required: ['groupId'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_join_group_by_invite',
    name: 'Join WhatsApp Group by Invite',
    description: 'Join a WhatsApp group using an invite code',
    modelDescription: 'Join a WhatsApp group using an invite code. Requires groupManagement capability.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        inviteCode: { type: 'string', description: 'Group invite code' },
      },
      required: ['inviteCode'],
    },
    composable: false,
    source: 'builtin',
  },

  // ═══ Phase 6.6 — Label Tools (Business accounts only) ═══
  {
    id: 'whatsapp_list_labels',
    name: 'List WhatsApp Labels',
    description: 'List all available WhatsApp labels (Business accounts only)',
    modelDescription: 'List all labels configured in the WhatsApp Business account. Requires labels capability (Business account). Returns "not supported" if the account is not a Business account.',
    category: CAT,
    riskLevel: 'low',
    schema: { type: 'object', properties: {}, required: [] },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_get_chat_labels',
    name: 'Get WhatsApp Chat Labels',
    description: 'Get labels assigned to a specific chat (Business accounts only)',
    modelDescription: 'Get all labels assigned to a specific chat. Requires labels capability (Business account).',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
      },
      required: ['chatId'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_add_label_to_chat',
    name: 'Add WhatsApp Label to Chat',
    description: 'Assign a label to a chat (Business accounts only)',
    modelDescription: 'Assign a label to a specific chat. Requires labels capability (Business account).',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        labelId: { type: 'string', description: 'Label ID to assign' },
      },
      required: ['chatId', 'labelId'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_remove_label_from_chat',
    name: 'Remove WhatsApp Label from Chat',
    description: 'Remove a label from a chat (Business accounts only)',
    modelDescription: 'Remove a label from a specific chat. Requires labels capability (Business account).',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        chatId: { type: 'string', description: 'WhatsApp chat JID' },
        labelId: { type: 'string', description: 'Label ID to remove' },
      },
      required: ['chatId', 'labelId'],
    },
    composable: false,
    source: 'builtin',
  },

  // ═══ Phase 6.7 — Status/Channel/Call/Profile Tools ═══
  {
    id: 'whatsapp_post_text_status',
    name: 'Post WhatsApp Text Status',
    description: 'Post a text status story (requires statusStories capability)',
    modelDescription: 'Post a text status story to WhatsApp. Requires statusStories capability. Returns "not supported" if the engine doesn\'t support status stories.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Status text content' },
      },
      required: ['text'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_post_image_status',
    name: 'Post WhatsApp Image Status',
    description: 'Post an image status story (requires statusStories capability)',
    modelDescription: 'Post an image status story to WhatsApp. Requires statusStories capability.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        filePath: { type: 'string', description: 'Path to the image file' },
        caption: { type: 'string', description: 'Caption text (optional)' },
      },
      required: ['filePath'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_list_status_updates',
    name: 'List WhatsApp Status Updates',
    description: 'List recent status updates from contacts (requires statusStories capability)',
    modelDescription: 'List recent status updates from contacts. Requires statusStories capability.',
    category: CAT,
    riskLevel: 'low',
    schema: { type: 'object', properties: {}, required: [] },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_subscribe_channel',
    name: 'Subscribe to WhatsApp Channel',
    description: 'Subscribe to a WhatsApp channel (requires channels capability)',
    modelDescription: 'Subscribe to a WhatsApp channel using an invite link. Requires channels capability.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        channelInvite: { type: 'string', description: 'Channel invite link or code' },
      },
      required: ['channelInvite'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_list_channels',
    name: 'List WhatsApp Channels',
    description: 'List subscribed WhatsApp channels (requires channels capability)',
    modelDescription: 'List all subscribed WhatsApp channels. Requires channels capability.',
    category: CAT,
    riskLevel: 'low',
    schema: { type: 'object', properties: {}, required: [] },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_reject_call',
    name: 'Reject WhatsApp Call',
    description: 'Reject an incoming WhatsApp call (requires rejectCall capability)',
    modelDescription: 'Reject an incoming WhatsApp voice/video call. Requires rejectCall capability. Use the callId from the incoming call event.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        callId: { type: 'string', description: 'ID of the call to reject' },
      },
      required: ['callId'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_set_profile_name',
    name: 'Set WhatsApp Profile Name',
    description: 'Set the WhatsApp display name',
    modelDescription: 'Set the WhatsApp profile display name (the name shown to others).',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'New profile name' },
      },
      required: ['name'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_set_profile_status',
    name: 'Set WhatsApp Profile Status',
    description: 'Set the WhatsApp about/status text',
    modelDescription: 'Set the WhatsApp profile status (about text shown in profile).',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        status: { type: 'string', description: 'New profile status/about text' },
      },
      required: ['status'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_set_profile_picture',
    name: 'Set WhatsApp Profile Picture',
    description: 'Set the WhatsApp profile picture',
    modelDescription: 'Set the WhatsApp profile picture from an image file.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        filePath: { type: 'string', description: 'Path to the image file' },
      },
      required: ['filePath'],
    },
    composable: false,
    source: 'builtin',
  },

  // ═══ Phase 6.8 — Webhook Tools ═══
  {
    id: 'whatsapp_create_webhook',
    name: 'Create WhatsApp Webhook',
    description: 'Register an external webhook to receive WhatsApp events',
    modelDescription: 'Register an external webhook endpoint that receives WhatsApp events (messages, acks, session status, etc.). The secret is used for HMAC-SHA256 payload signing. Events filter which events are sent (["*"] for all). This is for external integrations (n8n, CRM, etc.) — not needed for the agent itself.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Webhook URL (http or https)' },
        secret: { type: 'string', description: 'Secret for HMAC-SHA256 payload signing (optional)' },
        events: { type: 'array', items: { type: 'string' }, description: 'Event types to subscribe to (default: ["*"] for all)' },
        retryCount: { type: 'number', description: 'Number of delivery retries (default: 3)' },
      },
      required: ['url'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_list_webhooks',
    name: 'List WhatsApp Webhooks',
    description: 'List all registered WhatsApp webhooks',
    modelDescription: 'List all registered WhatsApp webhook endpoints with their URLs, event filters, and status.',
    category: CAT,
    riskLevel: 'low',
    schema: { type: 'object', properties: {}, required: [] },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_update_webhook',
    name: 'Update WhatsApp Webhook',
    description: 'Update a registered WhatsApp webhook',
    modelDescription: 'Update a WhatsApp webhook endpoint. Can change URL, events, active status, retry count, or secret. Only provided fields are updated.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        webhookId: { type: 'string', description: 'Webhook ID to update' },
        url: { type: 'string', description: 'New webhook URL (optional)' },
        events: { type: 'array', items: { type: 'string' }, description: 'New event filter (optional)' },
        active: { type: 'boolean', description: 'Enable/disable the webhook (optional)' },
        retryCount: { type: 'number', description: 'New retry count (optional)' },
        secret: { type: 'string', description: 'New signing secret (optional)' },
      },
      required: ['webhookId'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_delete_webhook',
    name: 'Delete WhatsApp Webhook',
    description: 'Delete a registered WhatsApp webhook',
    modelDescription: 'Permanently delete a WhatsApp webhook endpoint. All delivery failure records for this webhook are also deleted.',
    category: CAT,
    riskLevel: 'high',
    schema: {
      type: 'object',
      properties: {
        webhookId: { type: 'string', description: 'Webhook ID to delete' },
      },
      required: ['webhookId'],
    },
    composable: false,
    source: 'builtin',
    isDestructive: true,
  },
  {
    id: 'whatsapp_test_webhook',
    name: 'Test WhatsApp Webhook',
    description: 'Send a test event to a registered webhook',
    modelDescription: 'Send a test event to a WhatsApp webhook endpoint to verify it is reachable and accepting payloads correctly.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        webhookId: { type: 'string', description: 'Webhook ID to test' },
      },
      required: ['webhookId'],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_standing_order_list',
    name: 'List WhatsApp Standing Orders',
    description: 'List WhatsApp standing orders the owner has set',
    modelDescription: 'List standing orders that control how world WhatsApp messages are handled (brief, auto-reply as the owner, or ignore). Use when the owner asks which orders are active.',
    category: CAT,
    riskLevel: 'low',
    schema: {
      type: 'object',
      properties: {
        enabledOnly: { type: 'boolean', description: 'If true, only return enabled orders' },
      },
      required: [],
    },
    composable: true,
    source: 'builtin',
  },
  {
    id: 'whatsapp_standing_order_upsert',
    name: 'Save WhatsApp Standing Order',
    description: 'Create or update a WhatsApp standing order',
    modelDescription: 'Create or update a standing order. senders may be names, phones, or JIDs — they are resolved against the address book. If a name is ambiguous the tool fails; ask the owner which contact. action brief = notify the owner only; auto_reply = send replyTemplate as the owner then brief; ignore = drop. Never invent auto-replies without the owner asking for a standing order.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Existing order id to update (optional)' },
        title: { type: 'string', description: 'Short name, e.g. School pickup' },
        action: { type: 'string', enum: ['brief', 'auto_reply', 'ignore'], description: 'What to do when the match fires' },
        replyTemplate: { type: 'string', description: 'Exact text to send as the owner when action is auto_reply' },
        senders: { type: 'array', items: { type: 'string' }, description: 'People this order matches: saved name, business name, phone, or JID' },
        groups: { type: 'array', items: { type: 'string' }, description: 'Group JIDs this order matches' },
        keywords: { type: 'array', items: { type: 'string' }, description: 'Case-insensitive substrings in the message body' },
        chatKind: { type: 'string', enum: ['dm', 'group', 'any'], description: 'Restrict to DMs, groups, or any (default any)' },
        announceVoice: { type: 'boolean', description: 'Speak a voice interrupt when a voice session is active (default true)' },
        enabled: { type: 'boolean', description: 'Whether the order is active (default true)' },
        priority: { type: 'number', description: 'Tie-break when specificity is equal (higher wins)' },
      },
      required: ['title'],
    },
    composable: false,
    source: 'builtin',
  },
  {
    id: 'whatsapp_standing_order_revoke',
    name: 'Revoke WhatsApp Standing Order',
    description: 'Delete a WhatsApp standing order',
    modelDescription: 'Revoke a standing order by id or title, or revokeAll:true to clear every order. After revoke, world messages go back to briefing the owner only.',
    category: CAT,
    riskLevel: 'medium',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Order id to revoke' },
        title: { type: 'string', description: 'Order title to revoke (case-insensitive)' },
        revokeAll: { type: 'boolean', description: 'Delete all standing orders' },
      },
      required: [],
    },
    composable: false,
    source: 'builtin',
  },
];
