/**
 * Auto-generated migration registry.
 *
 * This file is generated by scripts/generate-migration-registry.mjs from the
 * SQL files in src/db/migrations/. Do not edit manually — add new .sql files
 * to the migrations directory and re-run the generator.
 *
 * Each migration is embedded as a string literal so it gets bundled into the
 * app by tsup/esbuild without needing runtime file access.
 */
import type { MigrationFile } from './MigrationRunner.js';

export const MIGRATION_FILES: MigrationFile[] = [
  { version: 1, name: 'core', sql: `-- Core schema: sessions, messages, crews, tokens, tasks, events, persona,
-- emotions, memories, skills, credentials, background tasks.
--
-- This is the squashed baseline representing the final state of all core
-- tables. No ALTER TABLE migrations needed — all columns are in their final
-- form from creation.

-- Ensure pgcrypto is available for gen_random_uuid() (built-in on PG 13+).
DO $$ BEGIN
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pgcrypto extension not available: %', SQLERRM;
END $$;

-- ─── Sessions ───────────────────────────────────────────────────────────────

CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL DEFAULT 'New Session',
  provider_id TEXT NOT NULL,
  model_id TEXT NOT NULL,
  scope_path TEXT NOT NULL,
  parent_id TEXT REFERENCES sessions(id),
  token_used INTEGER DEFAULT 0,
  token_available INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  compaction_count INTEGER NOT NULL DEFAULT 0,
  context_kind TEXT NOT NULL DEFAULT 'agent_x',
  host_crew_id TEXT,
  host_crew_name TEXT,
  host_crew_callsign TEXT,
  host_crew_title TEXT,
  host_crew_color TEXT,
  host_crew_catalog_id TEXT,
  host_crew_category_id TEXT,
  list_day_key TEXT,
  list_day_label TEXT,
  thinking_mode TEXT,
  output_mode TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sessions_crew_private ON sessions(host_crew_id, context_kind);

CREATE TABLE child_sessions (
  id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  parent_session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  kind TEXT NOT NULL DEFAULT 'sub_agent',
  label TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_child_sessions_parent ON child_sessions(parent_session_id);

-- ─── Messages ───────────────────────────────────────────────────────────────

CREATE TABLE messages (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  tool_calls TEXT,
  plan TEXT,
  parts TEXT,
  metadata TEXT,
  token_count INTEGER DEFAULT 0,
  attachments TEXT,
  archived_at TIMESTAMPTZ,
  platform_message_id BIGINT,
  platform_message_ids TEXT,
  platform_chat_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_messages_session ON messages(session_id);
CREATE INDEX idx_messages_session_created ON messages(session_id, created_at);
CREATE INDEX idx_messages_session_active ON messages(session_id, created_at) WHERE archived_at IS NULL;
CREATE INDEX idx_messages_platform_chat_id ON messages(platform_chat_id) WHERE platform_chat_id IS NOT NULL;

CREATE TABLE message_parts (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  message_id TEXT,
  type TEXT NOT NULL,
  content TEXT,
  tool_name TEXT,
  tool_call_id TEXT,
  tool_args TEXT,
  tool_result TEXT,
  tool_success INTEGER,
  usage_input INTEGER,
  usage_output INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_parts_session ON message_parts(session_id);
CREATE INDEX idx_message_parts_message_id ON message_parts(message_id);
CREATE INDEX idx_message_parts_session_created ON message_parts(session_id, created_at);

-- ─── Token logs ─────────────────────────────────────────────────────────────

CREATE TABLE token_logs (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  message_id TEXT,
  provider_id TEXT NOT NULL DEFAULT '',
  model_id TEXT NOT NULL,
  input_tokens INTEGER NOT NULL,
  output_tokens INTEGER NOT NULL,
  reasoning_tokens INTEGER DEFAULT 0,
  cost_usd REAL,
  crew_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_token_logs_session ON token_logs(session_id);

-- ─── Checkpoints ────────────────────────────────────────────────────────────

CREATE TABLE checkpoints (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  messages TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_checkpoints_session ON checkpoints(session_id);

-- ─── Session crew states ────────────────────────────────────────────────────

CREATE TABLE session_crew_states (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  crew_id TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  last_active TIMESTAMPTZ,
  message_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(session_id, crew_id)
);

CREATE INDEX idx_session_crew_states_session ON session_crew_states(session_id);

-- ─── Tool executions ────────────────────────────────────────────────────────

CREATE TABLE tool_executions (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  agent_task_id TEXT,
  tool_name TEXT NOT NULL,
  input TEXT NOT NULL,
  output TEXT,
  success INTEGER,
  elapsed_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tool_executions_session ON tool_executions(session_id);

-- ─── Session events ─────────────────────────────────────────────────────────

CREATE TABLE session_events (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL,
  event_type TEXT NOT NULL,
  payload TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_session_events_session ON session_events(session_id, sequence);

-- ─── Permission rules ───────────────────────────────────────────────────────

CREATE TABLE permission_rules (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  pattern TEXT NOT NULL DEFAULT '*',
  effect TEXT NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Agent tasks ────────────────────────────────────────────────────────────

CREATE TABLE agent_tasks (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  parent_id TEXT,
  instruction TEXT NOT NULL,
  tools TEXT,
  scope TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  result TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_tasks_session ON agent_tasks(session_id);

-- ─── Crews ──────────────────────────────────────────────────────────────────

CREATE TABLE crews (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  title TEXT,
  description TEXT NOT NULL DEFAULT '',
  system_prompt TEXT NOT NULL DEFAULT '',
  expertise TEXT,
  traits TEXT,
  tool_preferences TEXT,
  enabled_tools TEXT,
  disabled_tools TEXT,
  is_default INTEGER DEFAULT 0,
  metadata TEXT,
  source TEXT NOT NULL DEFAULT 'custom',
  catalog_id TEXT,
  search_text TEXT NOT NULL DEFAULT '',
  suggestable BOOLEAN NOT NULL DEFAULT TRUE,
  certifications TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FTS column on crews (generated tsvector)
ALTER TABLE crews ADD COLUMN search_tsv tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(search_text, ''))) STORED;

CREATE INDEX idx_crews_tsv ON crews USING GIN (search_tsv);
CREATE INDEX idx_crews_source ON crews(source);
CREATE UNIQUE INDEX idx_crews_catalog_id ON crews(catalog_id) WHERE catalog_id IS NOT NULL;

CREATE TABLE crew_feedback (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  crew_id TEXT NOT NULL,
  positive INTEGER NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_crew_feedback_crew ON crew_feedback(crew_id);

-- ─── Turn feedback ──────────────────────────────────────────────────────────

CREATE TABLE turn_feedback (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  message_id TEXT NOT NULL,
  context_kind TEXT NOT NULL DEFAULT 'agent_x',
  crew_id TEXT,
  rating TEXT NOT NULL,
  turn_summary TEXT,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(session_id, message_id)
);

CREATE INDEX idx_turn_feedback_session ON turn_feedback(session_id);
CREATE INDEX idx_turn_feedback_crew ON turn_feedback(crew_id);

-- ─── Session resume state ───────────────────────────────────────────────────

CREATE TABLE session_resume_state (
  session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  message_id TEXT NOT NULL,
  payload TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Bot credentials ────────────────────────────────────────────────────────

CREATE TABLE bot_credentials (
  platform TEXT PRIMARY KEY,
  config_enc TEXT NOT NULL,
  iv TEXT NOT NULL,
  tag TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT '1.0',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Skills ─────────────────────────────────────────────────────────────────

CREATE TABLE skills (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  trigger_patterns_json TEXT NOT NULL DEFAULT '[]',
  prompt TEXT NOT NULL DEFAULT '',
  tools_json TEXT NOT NULL DEFAULT '[]',
  is_bundled INTEGER NOT NULL DEFAULT 0,
  usage_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Agent persona ──────────────────────────────────────────────────────────

CREATE TABLE agent_persona (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  communication_style TEXT NOT NULL DEFAULT 'direct',
  decision_making TEXT NOT NULL DEFAULT 'balanced',
  domain_context TEXT NOT NULL DEFAULT '',
  traits TEXT NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Task snapshots ─────────────────────────────────────────────────────────

CREATE TABLE task_snapshots (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  session_id TEXT NOT NULL,
  task_id TEXT NOT NULL,
  step_index INTEGER NOT NULL DEFAULT 0,
  goal TEXT NOT NULL DEFAULT '',
  plan_state TEXT NOT NULL DEFAULT '{}',
  failure_history TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Agent growth / emotions / memories ─────────────────────────────────────

CREATE TABLE agent_experiences (
  id TEXT PRIMARY KEY,
  session_id TEXT,
  category TEXT,
  action TEXT,
  context TEXT,
  result TEXT,
  confidence REAL,
  reward REAL,
  correction TEXT,
  learnings TEXT,
  metadata TEXT,
  created_at TEXT
);

CREATE TABLE agent_growth_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  level TEXT DEFAULT 'Fresh',
  wisdom_score REAL DEFAULT 0,
  total_experiences INTEGER DEFAULT 0,
  total_interactions INTEGER DEFAULT 0,
  total_corrections INTEGER DEFAULT 0,
  avg_confidence REAL DEFAULT 0.5,
  emotional_range REAL DEFAULT 0,
  capabilities TEXT DEFAULT '[]',
  next_milestone_at INTEGER,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE agent_emotions (
  id TEXT PRIMARY KEY,
  mood TEXT,
  intensity REAL,
  context TEXT,
  session_id TEXT,
  source TEXT,
  trigger TEXT,
  valence REAL,
  created_at TEXT
);

CREATE INDEX idx_agent_emotions_source ON agent_emotions(source);
CREATE INDEX idx_agent_emotions_session ON agent_emotions(session_id);

CREATE TABLE agent_emotional_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  current_mood TEXT NOT NULL DEFAULT 'neutral',
  mood_intensity REAL NOT NULL DEFAULT 0.3,
  mood_since TEXT,
  baseline_mood TEXT NOT NULL DEFAULT 'neutral',
  emotional_range TEXT NOT NULL DEFAULT '[]',
  mood_decay_rate REAL NOT NULL DEFAULT 0.05,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO agent_emotional_state (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE agent_memories (
  id TEXT PRIMARY KEY,
  content TEXT,
  category TEXT,
  importance REAL,
  created_at TEXT
);

CREATE TABLE agent_diary (
  id TEXT PRIMARY KEY,
  entry TEXT,
  importance INTEGER,
  highlights TEXT,
  tags TEXT,
  created_at TEXT
);

CREATE TABLE agent_identity (
  id INTEGER PRIMARY KEY DEFAULT 1,
  interaction_count INTEGER DEFAULT 0
);

-- ─── Background tasks ───────────────────────────────────────────────────────

CREATE TABLE background_tasks (
  id TEXT PRIMARY KEY,
  parent_session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  child_session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  instruction TEXT NOT NULL,
  tools TEXT NOT NULL DEFAULT '[]',
  timeout INTEGER NOT NULL DEFAULT 60000,
  status TEXT NOT NULL DEFAULT 'queued',
  result TEXT,
  error TEXT,
  resource_usage TEXT,
  channel_context TEXT,
  background BOOLEAN NOT NULL DEFAULT true,
  consumed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX idx_background_tasks_parent_session ON background_tasks(parent_session_id);
CREATE INDEX idx_background_tasks_status ON background_tasks(status);
CREATE INDEX idx_background_tasks_created_at ON background_tasks(created_at DESC);
` },
  { version: 2, name: 'crew_catalog', sql: `-- Crew Hub catalog tables, full-text search, and session preferences.
-- Crew catalog data is seeded at application level from crew-catalog.manifest.json
-- (see catalog-seed-runner.ts) — no seed data in SQL.

CREATE TABLE crew_catalog (
  id              TEXT PRIMARY KEY,
  callsign        TEXT NOT NULL UNIQUE,
  name            TEXT NOT NULL,
  title           TEXT NOT NULL DEFAULT '',
  category_id     TEXT NOT NULL,
  category_label  TEXT NOT NULL DEFAULT '',
  description     TEXT NOT NULL DEFAULT '',
  system_prompt   TEXT NOT NULL DEFAULT '',
  tone            TEXT,
  expertise       TEXT,
  traits          TEXT,
  tools           TEXT,
  tags            TEXT,
  search_text     TEXT NOT NULL DEFAULT '',
  certifications  TEXT[] NOT NULL DEFAULT '{}',
  hub_revision    INTEGER NOT NULL DEFAULT 1,
  active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_crew_catalog_category ON crew_catalog(category_id);
CREATE INDEX idx_crew_catalog_callsign ON crew_catalog(callsign);
CREATE INDEX idx_crew_catalog_active ON crew_catalog(active);

-- FTS column on crew_catalog (generated tsvector)
ALTER TABLE crew_catalog ADD COLUMN search_tsv tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(search_text, ''))) STORED;

CREATE INDEX idx_crew_catalog_tsv ON crew_catalog USING GIN (search_tsv);

-- ─── App metadata (key-value store for catalog revision, etc.) ──────────────

CREATE TABLE app_metadata (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- ─── Session crew preferences (suggestion dismissal tracking) ───────────────

CREATE TABLE session_crew_preferences (
  session_id              TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  suggestions_dismissed   BOOLEAN NOT NULL DEFAULT FALSE,
  dismissed_at            TIMESTAMPTZ,
  last_suggestion_at      TIMESTAMPTZ,
  last_suggestion_turn_id TEXT,
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
` },
  { version: 3, name: 'automation_markdown_kb', sql: `-- Automation, notifications, markdown documents, knowledge base, pgvector,
-- voice realtime state, document templates, and document studio.

-- ─── Automation tasks ───────────────────────────────────────────────────────

CREATE TABLE automation_tasks (
  id TEXT PRIMARY KEY,
  task_key TEXT,
  display_id TEXT,
  title TEXT NOT NULL,
  instruction TEXT NOT NULL,
  schedule_type TEXT NOT NULL CHECK (schedule_type IN ('once', 'recurring')),
  cron_expression TEXT,
  run_at TIMESTAMPTZ,
  timezone TEXT NOT NULL DEFAULT 'UTC',
  status TEXT NOT NULL DEFAULT 'active',
  source_channel TEXT NOT NULL DEFAULT 'web',
  source_session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  notify_channels JSONB NOT NULL DEFAULT '["in_app"]'::jsonb,
  permission_snapshot JSONB,
  pgboss_job_id TEXT,
  pgboss_schedule_name TEXT,
  last_run_at TIMESTAMPTZ,
  last_run_status TEXT,
  next_run_at TIMESTAMPTZ,
  run_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_automation_tasks_status ON automation_tasks(status);
CREATE INDEX idx_automation_tasks_session ON automation_tasks(source_session_id);
CREATE UNIQUE INDEX idx_automation_tasks_active_key ON automation_tasks(task_key) WHERE task_key IS NOT NULL AND status = 'active';
CREATE UNIQUE INDEX idx_automation_tasks_display_id ON automation_tasks(display_id) WHERE display_id IS NOT NULL;

CREATE TABLE automation_run_logs (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES automation_tasks(id) ON DELETE CASCADE,
  run_id TEXT NOT NULL,
  level TEXT NOT NULL,
  label TEXT NOT NULL,
  detail TEXT,
  event_type TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_automation_run_logs_task_created ON automation_run_logs(task_id, created_at);
CREATE INDEX idx_automation_run_logs_run ON automation_run_logs(run_id, created_at);

CREATE TABLE automation_session_confirmations (
  session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  confirmed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  confirmation_note TEXT
);

-- ─── Notifications ──────────────────────────────────────────────────────────

CREATE TABLE notifications (
  id TEXT PRIMARY KEY,
  task_id TEXT REFERENCES automation_tasks(id) ON DELETE SET NULL,
  kind TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  payload JSONB,
  channels JSONB NOT NULL DEFAULT '["in_app"]'::jsonb,
  delivery_status JSONB NOT NULL DEFAULT '{}'::jsonb,
  read_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_created ON notifications(created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(read_at) WHERE read_at IS NULL AND dismissed_at IS NULL;
CREATE INDEX idx_notifications_active ON notifications(created_at DESC) WHERE dismissed_at IS NULL;

-- ─── Markdown documents ─────────────────────────────────────────────────────

CREATE TABLE markdowns (
  id TEXT PRIMARY KEY,
  session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  message_id TEXT,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL DEFAULT '',
  file_path TEXT NOT NULL,
  content_format TEXT NOT NULL DEFAULT 'markdown',
  source_role TEXT,
  compile_error TEXT,
  list_day_key TEXT,
  list_day_label TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_markdowns_created ON markdowns(created_at DESC);
CREATE INDEX idx_markdowns_session ON markdowns(session_id, created_at DESC);

-- ─── Knowledge base ─────────────────────────────────────────────────────────

CREATE TABLE knowledge_sources (
  id TEXT PRIMARY KEY,
  session_id TEXT,
  name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size INTEGER NOT NULL DEFAULT 0,
  storage_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  progress INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  summary TEXT,
  chunk_count INTEGER,
  page_count INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_knowledge_sources_session ON knowledge_sources(session_id);
CREATE INDEX idx_knowledge_sources_status ON knowledge_sources(status);
CREATE INDEX idx_knowledge_sources_created_at ON knowledge_sources(created_at DESC);

CREATE TABLE knowledge_chunks (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL REFERENCES knowledge_sources(id) ON DELETE CASCADE,
  index INTEGER NOT NULL,
  content TEXT NOT NULL,
  embedding JSONB,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(source_id, index)
);

CREATE INDEX idx_knowledge_chunks_source ON knowledge_chunks(source_id);
CREATE INDEX idx_knowledge_chunks_source_index ON knowledge_chunks(source_id, index);

CREATE TABLE knowledge_pages (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL REFERENCES knowledge_sources(id) ON DELETE CASCADE,
  page_number INTEGER NOT NULL,
  content TEXT NOT NULL,
  summary TEXT,
  embedding JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(source_id, page_number)
);

CREATE INDEX idx_knowledge_pages_source ON knowledge_pages(source_id);

CREATE TABLE knowledge_source_status_events (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL REFERENCES knowledge_sources(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  progress INTEGER NOT NULL DEFAULT 0,
  detail TEXT,
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_knowledge_status_events_source ON knowledge_source_status_events(source_id);

-- ─── pgvector (optional — app degrades to in-memory store if unavailable) ──

DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS vector;
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
    CREATE TABLE knowledge_chunk_vectors (
      id TEXT PRIMARY KEY,
      source_id TEXT NOT NULL,
      chunk_id TEXT NOT NULL,
      content TEXT NOT NULL,
      metadata JSONB,
      embedding vector(1536)
    );
    CREATE INDEX idx_knowledge_chunk_vectors_source ON knowledge_chunk_vectors(source_id);
    CREATE INDEX idx_knowledge_chunk_vectors_embedding ON knowledge_chunk_vectors USING ivfflat (embedding vector_cosine_ops);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END $$;

-- ─── Voice realtime state ───────────────────────────────────────────────────

CREATE TABLE voice_realtime_state (
  session_id TEXT PRIMARY KEY,
  xai_conversation_id TEXT,
  xai_conversation_updated_at TIMESTAMPTZ,
  last_voice_active_at TIMESTAMPTZ,
  summary TEXT,
  summary_updated_at TIMESTAMPTZ,
  summary_source_message_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_voice_realtime_last_active ON voice_realtime_state (last_voice_active_at DESC NULLS LAST);

-- ─── Document templates ─────────────────────────────────────────────────────

CREATE TABLE document_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  mime_type TEXT NOT NULL,
  size INTEGER NOT NULL DEFAULT 0,
  storage_id TEXT NOT NULL,
  format TEXT NOT NULL DEFAULT 'other',
  fillable BOOLEAN NOT NULL DEFAULT FALSE,
  fields JSONB NOT NULL DEFAULT '[]'::jsonb,
  tags TEXT[] NOT NULL DEFAULT '{}',
  analysis_status TEXT NOT NULL DEFAULT 'ready',
  analysis_error TEXT,
  design_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_document_templates_name ON document_templates (name);
CREATE INDEX idx_document_templates_updated ON document_templates (updated_at DESC);

-- ─── Document Studio ────────────────────────────────────────────────────────

CREATE TABLE doc_masters (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'layout',
  format TEXT NOT NULL DEFAULT 'other',
  mime_type TEXT NOT NULL,
  storage_id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  analysis JSONB,
  analysis_state TEXT NOT NULL DEFAULT 'pending',
  analysis_error TEXT,
  tags TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_doc_masters_kind ON doc_masters (kind);
CREATE INDEX idx_doc_masters_updated ON doc_masters (updated_at DESC);

CREATE TABLE doc_binders (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  slots JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_doc_binders_name ON doc_binders (name);

CREATE TABLE doc_answer_sets (
  id TEXT PRIMARY KEY,
  values JSONB NOT NULL DEFAULT '{}'::jsonb,
  provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE doc_mappings (
  id TEXT PRIMARY KEY,
  data_master_id TEXT NOT NULL,
  schema_ref TEXT NOT NULL,
  entries JSONB NOT NULL DEFAULT '[]'::jsonb,
  confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE doc_jobs (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  spec JSONB NOT NULL,
  recipe_id TEXT,
  binder_id TEXT,
  progress_done INTEGER NOT NULL DEFAULT 0,
  progress_total INTEGER NOT NULL DEFAULT 0,
  progress_detail TEXT,
  artifacts JSONB NOT NULL DEFAULT '[]'::jsonb,
  manifest_id TEXT,
  step_results JSONB NOT NULL DEFAULT '{}'::jsonb,
  error TEXT,
  cancelled BOOLEAN NOT NULL DEFAULT false,
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_doc_jobs_status ON doc_jobs (status);
CREATE INDEX idx_doc_jobs_updated ON doc_jobs (updated_at DESC);

CREATE TABLE doc_instances (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  index INTEGER NOT NULL,
  binding_set_id TEXT,
  path TEXT,
  master_id TEXT,
  status TEXT NOT NULL DEFAULT 'planned',
  error TEXT
);

CREATE INDEX idx_doc_instances_job ON doc_instances (job_id);

CREATE TABLE doc_artifacts (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  instance_index INTEGER,
  path TEXT NOT NULL,
  storage_id TEXT,
  format TEXT NOT NULL,
  checksum TEXT NOT NULL,
  binding_set_id TEXT,
  evidence_map JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_doc_artifacts_job ON doc_artifacts (job_id);

CREATE TABLE doc_manifests (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  rows JSONB NOT NULL DEFAULT '[]'::jsonb,
  summary_ok INTEGER NOT NULL DEFAULT 0,
  summary_failed INTEGER NOT NULL DEFAULT 0,
  summary_skipped INTEGER NOT NULL DEFAULT 0
);
` },
  { version: 4, name: 'whatsapp', sql: `-- WhatsApp channel: session lifecycle, Baileys credential storage, message log,
-- LID<->phone identity mapping, and external webhook subsystem.
--
-- Exactly one WhatsApp session is supported per Agent-X install (by application
-- convention, not a hard schema constraint).

CREATE TABLE whatsapp_session (
  id TEXT PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'disconnected',
  engine TEXT NOT NULL DEFAULT 'baileys',
  phone_number TEXT,
  push_name TEXT,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  connected_at TIMESTAMPTZ,
  last_active_at TIMESTAMPTZ
);

-- Baileys credential storage: creds (single blob) + signal keys (per-row)
CREATE TABLE whatsapp_creds (
  id TEXT PRIMARY KEY DEFAULT 'default',
  creds_enc TEXT NOT NULL,
  iv TEXT NOT NULL,
  tag TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE whatsapp_signal_keys (
  category TEXT NOT NULL,
  key_id TEXT NOT NULL,
  value_enc TEXT NOT NULL,
  iv TEXT NOT NULL,
  tag TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (category, key_id)
);

-- LID <-> phone number mapping (WhatsApp multi-device identity quirk)
CREATE TABLE whatsapp_lid_mapping (
  lid TEXT PRIMARY KEY,
  phone TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Message log
CREATE TABLE whatsapp_messages (
  id TEXT PRIMARY KEY,
  wa_message_id TEXT NOT NULL,
  chat_id TEXT NOT NULL,
  direction TEXT NOT NULL,
  "from" TEXT NOT NULL,
  "to" TEXT NOT NULL,
  body TEXT,
  type TEXT NOT NULL DEFAULT 'text',
  status TEXT NOT NULL DEFAULT 'pending',
  timestamp BIGINT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_whatsapp_messages_wa_id ON whatsapp_messages(wa_message_id);
CREATE INDEX idx_whatsapp_messages_timestamp ON whatsapp_messages(timestamp);
CREATE INDEX idx_whatsapp_messages_chat ON whatsapp_messages(chat_id, timestamp);

-- External webhook subscriptions
CREATE TABLE whatsapp_webhooks (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  events TEXT[] NOT NULL DEFAULT ARRAY['*']::text[],
  secret_enc TEXT,
  secret_iv TEXT,
  secret_tag TEXT,
  headers JSONB NOT NULL DEFAULT '{}'::jsonb,
  filters JSONB,
  active BOOLEAN NOT NULL DEFAULT true,
  retry_count INTEGER NOT NULL DEFAULT 3,
  last_triggered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Webhook delivery failure / dead-letter bookkeeping
CREATE TABLE whatsapp_webhook_failures (
  id TEXT PRIMARY KEY,
  webhook_id TEXT NOT NULL REFERENCES whatsapp_webhooks(id) ON DELETE CASCADE,
  event TEXT NOT NULL,
  url TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  delivery_id TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_status_code INTEGER,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_whatsapp_webhook_failures_webhook ON whatsapp_webhook_failures(webhook_id);
CREATE INDEX idx_whatsapp_webhook_failures_created ON whatsapp_webhook_failures(created_at);
` },
  { version: 5, name: 'observability', sql: `-- Observability schema: traces, spans, logs, metric samples, config, OTLP,
-- alerting, and cost analytics rollup.
--
-- DOMAIN SEGREGATION: every row is tagged with \`domain\` ∈ ('APP','AGENT'):
--   AGENT = AI/LLM turn lifecycle (turns, journey, llm calls, tool decisions, crew, retrieval)
--   APP   = normal application operations (HTTP, auth, DB, WebSocket, channels, automation, startup)

CREATE SCHEMA IF NOT EXISTS observability;

-- 1. TRACES — one row per turn (AGENT) or per app request/operation (APP)
CREATE TABLE observability.traces (
  trace_id        TEXT PRIMARY KEY,
  root_span_id    TEXT NOT NULL,
  domain          TEXT NOT NULL CHECK(domain IN ('APP','AGENT')) DEFAULT 'AGENT',
  kind            TEXT NOT NULL,
  session_id      TEXT,
  turn_id         TEXT,
  user_text       TEXT,
  status          TEXT NOT NULL CHECK(status IN ('running','ok','error','cancelled')),
  error           TEXT,
  started_at      TIMESTAMPTZ NOT NULL,
  ended_at        TIMESTAMPTZ,
  duration_ms     INTEGER,
  provider        TEXT,
  model           TEXT,
  input_tokens    INTEGER,
  output_tokens   INTEGER,
  tool_call_count INTEGER NOT NULL DEFAULT 0,
  cost_usd        NUMERIC(12,6) NOT NULL DEFAULT 0
);

CREATE INDEX idx_traces_session_started ON observability.traces (session_id, started_at DESC);
CREATE INDEX idx_traces_status_started ON observability.traces (status, started_at DESC);
CREATE INDEX idx_traces_kind_started ON observability.traces (kind, started_at DESC);
CREATE INDEX idx_traces_domain_started ON observability.traces (domain, started_at DESC);

-- 2. SPANS — the tree (llm, tool, tool_decision, journey_stage, agent, retrieval, internal)
CREATE TABLE observability.spans (
  span_id         TEXT PRIMARY KEY,
  trace_id        TEXT NOT NULL REFERENCES observability.traces(trace_id) ON DELETE CASCADE,
  parent_span_id  TEXT,
  domain          TEXT NOT NULL CHECK(domain IN ('APP','AGENT')) DEFAULT 'AGENT',
  name            TEXT NOT NULL,
  kind            TEXT NOT NULL,
  status          TEXT NOT NULL CHECK(status IN ('ok','error','unset')),
  started_at      TIMESTAMPTZ NOT NULL,
  ended_at        TIMESTAMPTZ,
  duration_ms     INTEGER,
  attributes      JSONB NOT NULL DEFAULT '{}'::jsonb,
  events          JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE INDEX idx_spans_trace_started ON observability.spans (trace_id, started_at);
CREATE INDEX idx_spans_parent ON observability.spans (parent_span_id);
CREATE INDEX idx_spans_domain ON observability.spans (domain);

-- 3. LOGS — structured, linked to trace/span, tagged by domain
CREATE TABLE observability.logs (
  id           BIGSERIAL PRIMARY KEY,
  trace_id     TEXT,
  span_id      TEXT,
  session_id   TEXT,
  domain       TEXT NOT NULL CHECK(domain IN ('APP','AGENT')) DEFAULT 'AGENT',
  ts           TIMESTAMPTZ NOT NULL,
  level        TEXT NOT NULL CHECK(level IN ('debug','info','warn','error')),
  scope        TEXT,
  message      TEXT NOT NULL,
  payload      JSONB
);

CREATE INDEX idx_logs_trace_ts ON observability.logs (trace_id, ts);
CREATE INDEX idx_logs_ts ON observability.logs (ts DESC);
CREATE INDEX idx_logs_session_ts ON observability.logs (session_id, ts DESC);
CREATE INDEX idx_logs_domain_ts ON observability.logs (domain, ts DESC);

-- 4. METRIC SAMPLES — time-series for UI charts
CREATE TABLE observability.metric_samples (
  id         BIGSERIAL PRIMARY KEY,
  ts         TIMESTAMPTZ NOT NULL,
  name       TEXT NOT NULL,
  value      DOUBLE PRECISION NOT NULL,
  labels     JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX idx_metrics_name_ts ON observability.metric_samples (name, ts DESC);
CREATE INDEX idx_metrics_domain_ts ON observability.metric_samples ((labels->>'domain'), ts DESC);

-- 5. CONFIG — single row (id=1) with OTLP and alerting settings
CREATE TABLE observability.config (
  id                      INT PRIMARY KEY DEFAULT 1 CHECK(id = 1),
  retention_days          INT NOT NULL DEFAULT 30 CHECK(retention_days BETWEEN 1 AND 90),
  capture_prompts         BOOLEAN NOT NULL DEFAULT TRUE,
  enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
  otlp_enabled            BOOLEAN NOT NULL DEFAULT FALSE,
  otlp_endpoint           TEXT    NOT NULL DEFAULT 'http://localhost:4318/v1/traces',
  otlp_protocol           TEXT    NOT NULL DEFAULT 'http' CHECK(otlp_protocol IN ('http', 'grpc')),
  otlp_headers            JSONB   NOT NULL DEFAULT '{}'::jsonb,
  alerting_enabled        BOOLEAN NOT NULL DEFAULT FALSE,
  alerting_error_rate_pct INT     NOT NULL DEFAULT 10  CHECK(alerting_error_rate_pct BETWEEN 1 AND 100),
  alerting_latency_p95_ms INT     NOT NULL DEFAULT 30000 CHECK(alerting_latency_p95_ms BETWEEN 100 AND 600000),
  alerting_window_minutes INT     NOT NULL DEFAULT 15  CHECK(alerting_window_minutes BETWEEN 1 AND 1440)
);

INSERT INTO observability.config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 6. Cost analytics rollup (materialized view, refreshed on-demand)
CREATE MATERIALIZED VIEW observability.cost_rollup_daily AS
  SELECT
    date_trunc('day', started_at)::date              AS day,
    COALESCE(provider, 'unknown')                    AS provider,
    COALESCE(model, 'unknown')                       AS model,
    domain,
    COUNT(*)                                         AS trace_count,
    SUM(input_tokens)                                AS total_input_tokens,
    SUM(output_tokens)                               AS total_output_tokens,
    SUM(cost_usd)                                    AS total_cost_usd,
    AVG(duration_ms)                                 AS avg_duration_ms
  FROM observability.traces
  WHERE cost_usd IS NOT NULL
  GROUP BY 1, 2, 3, 4
  ORDER BY 1 DESC, 2, 3;

CREATE UNIQUE INDEX idx_cost_rollup_daily
  ON observability.cost_rollup_daily (day, provider, model, domain);

-- 7. Alerts — persisted alert events
CREATE TABLE observability.alerts (
  id          BIGSERIAL PRIMARY KEY,
  triggered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  type        TEXT NOT NULL CHECK(type IN ('error_rate', 'latency_p95')),
  severity    TEXT NOT NULL DEFAULT 'warning' CHECK(severity IN ('info', 'warning', 'critical')),
  message     TEXT NOT NULL,
  threshold   INT NOT NULL,
  actual      INT NOT NULL,
  window_minutes INT NOT NULL,
  resolved    BOOLEAN NOT NULL DEFAULT FALSE,
  resolved_at TIMESTAMPTZ
);

CREATE INDEX idx_alerts_unresolved ON observability.alerts (resolved, triggered_at DESC) WHERE NOT resolved;
CREATE INDEX idx_alerts_triggered ON observability.alerts (triggered_at DESC);
` },
  { version: 6, name: 'prime_adoption', sql: `-- Prime Agent adoption schema (V006)
-- Harness, goals, durable turns, leases, command journal, inter-agent messaging, resident sessions

-- ─── Continual Harness ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS harness_entries (
  id TEXT PRIMARY KEY,
  session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE,
  scope TEXT NOT NULL DEFAULT 'local' CHECK (scope IN ('local', 'global')),
  kind TEXT NOT NULL CHECK (kind IN ('prompt', 'memory', 'skill', 'subagent')),
  title TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  path TEXT NOT NULL DEFAULT '',
  reference JSONB NOT NULL DEFAULT '{}'::jsonb,
  arguments JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT '',
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_harness_entries_session_kind
  ON harness_entries(session_id, kind);
CREATE INDEX IF NOT EXISTS idx_harness_entries_scope_kind
  ON harness_entries(scope, kind);

CREATE TABLE IF NOT EXISTS harness_refinements (
  id TEXT PRIMARY KEY,
  session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  scope TEXT NOT NULL DEFAULT 'local',
  trigger TEXT NOT NULL DEFAULT '',
  changes JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence TEXT NOT NULL DEFAULT '',
  outcome TEXT NOT NULL DEFAULT '',
  rollback_id TEXT,
  before_snapshot JSONB,
  after_snapshot JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_harness_refinements_session
  ON harness_refinements(session_id, created_at DESC);

-- ─── Persistent Goals ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS session_goals (
  session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'idle',
  objective TEXT NOT NULL DEFAULT '',
  progress JSONB NOT NULL DEFAULT '{}'::jsonb,
  budget JSONB NOT NULL DEFAULT '{}'::jsonb,
  continuations_used INTEGER NOT NULL DEFAULT 0,
  tokens_used INTEGER NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  error TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Durable Turns ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS durable_turns (
  turn_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'queued',
  generation INTEGER NOT NULL DEFAULT 0,
  sequence INTEGER NOT NULL DEFAULT 0,
  partial_content TEXT,
  error TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_durable_turns_session_status
  ON durable_turns(session_id, status);

CREATE TABLE IF NOT EXISTS turn_checkpoints (
  id TEXT PRIMARY KEY,
  turn_id TEXT NOT NULL REFERENCES durable_turns(turn_id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL,
  parts JSONB NOT NULL DEFAULT '[]'::jsonb,
  partial_content TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_turn_checkpoints_turn
  ON turn_checkpoints(turn_id, sequence);

-- ─── Session Leases ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS session_leases (
  session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  owner_id TEXT NOT NULL,
  holder_pid INTEGER,
  holder_instance TEXT,
  acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

-- ─── Command Journal ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS command_journal (
  id TEXT PRIMARY KEY,
  idempotency_key TEXT NOT NULL UNIQUE,
  command_type TEXT NOT NULL,
  session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'received',
  result JSONB,
  error TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_command_journal_session
  ON command_journal(session_id, received_at DESC);

-- ─── Inter-agent Messaging ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS agent_messages (
  id TEXT PRIMARY KEY,
  from_session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  to_session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  topic TEXT NOT NULL DEFAULT 'default',
  delivery_mode TEXT NOT NULL DEFAULT 'auto',
  receiver_role TEXT NOT NULL DEFAULT 'sibling',
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  delivered_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_agent_messages_to
  ON agent_messages(to_session_id, created_at DESC);

-- ─── WS Generation / Resident Sessions ─────────────────────────────────────

CREATE TABLE IF NOT EXISTS session_generations (
  session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  generation INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS resident_sessions (
  session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active',
  detached_at TIMESTAMPTZ,
  last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  idle_timeout_ms INTEGER NOT NULL DEFAULT 86400000,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
` },
  { version: 7, name: 'session_events', sql: `-- Session event log for WS generation replay (Prime Agent adoption Phase 2)
-- session_events already exists from V001 (event_type + TEXT payload); extend it.

ALTER TABLE session_events
  ADD COLUMN IF NOT EXISTS generation INTEGER NOT NULL DEFAULT 0;

-- Adoption replay rows omit event_type; legacy rows keep event_type populated.
ALTER TABLE session_events
  ALTER COLUMN event_type DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_session_events_replay
  ON session_events(session_id, generation, sequence);
` },
  { version: 8, name: 'automation_scheduler_claims', sql: `-- Phase 3 scheduler hardening: claim-before-deliver + run records

ALTER TABLE automation_tasks
  ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS claimed_by TEXT;

CREATE TABLE IF NOT EXISTS automation_runs (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES automation_tasks(id) ON DELETE CASCADE,
  trigger TEXT NOT NULL DEFAULT 'schedule',
  status TEXT NOT NULL,
  coalesced BOOLEAN NOT NULL DEFAULT FALSE,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_automation_runs_task_started
  ON automation_runs(task_id, started_at DESC);
` },
];
