import type { ToolResult } from '@agentx/shared';

export interface SubAgentToolCallRecord {
  name: string;
  args: Record<string, unknown>;
  result: ToolResult;
  elapsed: number;
}

export interface SubAgentVerificationResult {
  verified: boolean;
  /** Human-readable reason the result is considered unverified (only set when verified=false). */
  reason?: string;
}

/** Tool ID name fragments that indicate a real, verifiable workspace mutation. */
const MUTATING_TOOL_RE = /(^|_)(write|create|edit|commit|replace|insert|delete|push|patch|move)(_|$)/i;

export function isMutatingToolCall(toolName: string): boolean {
  return MUTATING_TOOL_RE.test(toolName);
}

/**
 * Evaluate whether a sub-agent's own tool-call log supports the completion it
 * is reporting, or contradicts it.
 *
 * A sub-agent's final text is generated by the model narrating what it
 * *believes* it did — this is model output, not ground truth. The tool-call
 * log (what actually got dispatched and what each call's ToolResult really
 * was) is ground truth. If every file/workspace-mutating tool call the
 * sub-agent attempted failed, or it never touched a tool at all despite
 * being handed a non-empty allow-list, that mismatch should be surfaced
 * loudly rather than silently trusted.
 */
export function evaluateSubAgentVerification(
  toolCallsLog: SubAgentToolCallRecord[],
  allowedTools: string[],
): SubAgentVerificationResult {
  const mutating = toolCallsLog.filter((t) => isMutatingToolCall(t.name));
  const mutatingAllFailed = mutating.length > 0 && mutating.every((t) => !t.result.success);
  const noToolsAttemptedAtAll = toolCallsLog.length === 0 && allowedTools.length > 0;

  if (!mutatingAllFailed && !noToolsAttemptedAtAll) {
    return { verified: true };
  }

  const reason = mutatingAllFailed
    ? `all ${mutating.length} file/workspace-mutating tool call(s) it attempted failed (e.g. ${mutating[0]!.result.error ?? mutating[0]!.result.output.slice(0, 120)})`
    : `it was given tools (${allowedTools.join(', ')}) but never called any of them`;

  return { verified: false, reason };
}

/** Prepend a loud, unmistakable warning when a sub-agent's report is unverified. */
export function applySubAgentVerificationGuard(
  output: string,
  toolCallsLog: SubAgentToolCallRecord[],
  allowedTools: string[],
): string {
  const verification = evaluateSubAgentVerification(toolCallsLog, allowedTools);
  if (verification.verified) return output;

  const warning = [
    `[VERIFICATION WARNING] This sub-agent's own tool-call log contradicts its summary below — ${verification.reason}.`,
    'Treat this result as UNVERIFIED. Do not relay it to the user as completed work;',
    'independently confirm the claimed files/changes exist before reporting success.',
  ].join(' ');

  return `${warning}\n\n${output}`;
}
